spring.application.name=Inventory

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=IMS
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.port=8086

# ✅ Mail properties (commented for now)
spring.mail.host=localhost
spring.mail.port=2526
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

logging.level.org.springframework.security=DEBUG
